### ISSUE TITLE
Allow filtering by severity

### ISSUE THREAD

**Issue by evilpacket** [npm/npm-audit-report#13]
It would be nice if reporters took in an optional severity level and only produced output for vulnerabilities at or above that severity level.

**Comment by mdix** [comment]
I'd like to take this one. I implemented some things in preparation for this one, so as soon as we merged the others I'd work on it.

**Comment by llaenowyd** [comment]
bump

**Comment by llaenowyd** [comment]
this appears dead - the changes linked above by @welwood08 are not on a PR and are against a read-only, abandoned version of npm

**Comment by nazreen** [comment]
let's get this back on track!

**Comment by WilliamDASILVA** [comment]
For future Googlers, you can filter by severity using the `--audit-level` attribute.

```bash
npm audit --audit-level=moderate
```

Make sure you have a recent npm version.

**Comment by k3n** [comment]
@WilliamDASILVA According to the [NPM docs](https://docs.npmjs.com/cli/audit), and my testing, that's not how it works -- it doesn't filter anything, it merely determines what is considered a failure:

```
Fail an audit only if the results include a vulnerability with a level of moderate or higher:

$ npm audit --audit-level=moderate
```

**Comment by isaacs** [comment]
Closing out all issues and PRs from 2018 and 2019, since this module has been fundamentally refactored for version 2 (npm version 7).  Happy to reopen if this is still a thing worth exploring (and it'll probably be easier now if so).
