### ISSUE TITLE
JSON reporter returns exit code 0 in any case

### ISSUE THREAD

**Issue by mdix** [npm/npm-audit-report#19]
Is it an intended behaviour that the JSON reporter always returns an exit code of 0, indepentend of the number of vulnerarbilities found? If it's a bug I'd be happy to commit a fix.

https://github.com/npm/npm-audit-report/blob/latest/reporters/json.js#L13

**Comment by isaacs** [comment]
Closing out all issues and PRs from 2018 and 2019, since this module has been fundamentally refactored for version 2 (npm version 7).  Happy to reopen if this is still a thing worth exploring (and it'll probably be easier now if so).
