### ISSUE TITLE
Unused securityThreshold property

### ISSUE THREAD

**Issue by mdix** [npm/npm-audit-report#20]
Why is [this](https://github.com/npm/npm-audit-report/blob/4777889adf2023d098e6561021e197eba3f4789e/reporters/install.js#L25) and [this](https://github.com/npm/npm-audit-report/blob/4a4023de83c34700e2bf2e8c68e1af4832a1123a/reporters/detail.js#L9) there? It's not used anywhere (and as far as I can see also not passed on to any library or something).

**Comment by isaacs** [comment]
Closing out all issues and PRs from 2018 and 2019, since this module has been fundamentally refactored for version 2 (npm version 7).  Happy to reopen if this is still a thing worth exploring (and it'll probably be easier now if so).
