### ISSUE TITLE
Add reference or examples of how to get a NSP response.

### ISSUE THREAD

**Issue by metaa** [npm/npm-audit-report#27]
I tried implementing this for a project of mine but I really can't find how to get an actual response from the NSP API, nothing really seems to mention it anywhere.

For people having the same problems it would really be appreciated if someone posted an actual code example or at least reference pointing out how to get an actual response from it.

Thanks

**Comment by isaacs** [comment]
Closing out all issues and PRs from 2018 and 2019, since this module has been fundamentally refactored for version 2 (npm version 7).  Happy to reopen if this is still a thing worth exploring (and it'll probably be easier now if so).
