### ISSUE TITLE
Tag pre-release advisories in report

### ISSUE THREAD

**Issue by evilpacket** [npm/npm-audit-report#3]
Authenticated, paid npm users get access to additional data, this should be called out in the report.

**Comment by evilpacket** [comment]
Going to wait until report formats shake out a bit more to proceed with doing this.

**Comment by isaacs** [comment]
Closing out all issues and PRs from 2018 and 2019, since this module has been fundamentally refactored for version 2 (npm version 7).  Happy to reopen if this is still a thing worth exploring (and it'll probably be easier now if so).
