### ISSUE TITLE
Fix high vulnerability

### ISSUE THREAD

**Issue by brainlulz** [npm/npm-audit-report#33]
Node version: 8.11.1
NPM version: 6.4.1

Steps to reproduce: 
- Clone the repository
- Run `npm install`

It warn that the repository have a high severity vulnerability.

I run an `npm audit` to see what is that vulnerability and here is the output: [Image of the output](http://image.noelshack.com/fichiers/2018/49/3/1544003817-capture-d-ecran-2018-12-05-a-10-39-26.png)

To fix it, I run the command `npm update cryptiles --depth 5` as recommanded and it fixed it (I run `npm test` after and everything pass).

**Comment by zkat** [comment]
This has been fixed with `npm audit fix` as of v1.3.2. Cheers!
