### ISSUE TITLE
add .auditrc same as .nsprc

### ISSUE THREAD

**Issue by TrejGun** [npm/npm-audit-report#37]
Hi there, thx for this tool

I want to be notified about new vulnerabilities but dont want to be notified about already known or vulnerabilities in devDependencies so i want to be able to disable them one by one

**Comment by isaacs** [comment]
Closing out all issues and PRs from 2018 and 2019, since this module has been fundamentally refactored for version 2 (npm version 7).  Happy to reopen if this is still a thing worth exploring (and it'll probably be easier now if so).
