### ISSUE TITLE
[FEATURE] Swap high and critical colors

### ISSUE THREAD

**Issue by moltar** [npm/npm-audit-report#41]
# What / Why

I propose to swap the colors of `high` and `critical` counters.

It seems like `critical` is more important, yet is less visible.

Another potential solution is to color `high` in yellow / orange (warning), and `critical` in red.

## When

* n/a

## Where

`npm audit`

### Current Behavior

* `high` count is red
* `critical` count is purple

<img width="276" alt="image" src="https://user-images.githubusercontent.com/491247/71173165-4cde5500-2262-11ea-83f1-70359ec4f6c6.png">

### Expected Behavior

* `high` count is purple
* `critical` count is red

## Who

* n/a

## References

* n/a

**Comment by isaacs** [comment]
I think if we're going to start changing colors, we should probably go with using 256-color ansi codes, and we'd also have to set a background, for accessibility purposes.

You can change what "purple" means in your terminal.  A pretty typical default looks like this: 
<img width="390" alt="Screenshot 2020-05-07 17 43 36" src="https://user-images.githubusercontent.com/9287/81358071-4f630f00-908a-11ea-8b75-c2bead7b244b.png">
