### ISSUE TITLE
What does the N and Y letters mean at the end of npm audit --parseable in npm 6?

### ISSUE THREAD

**Issue by Uko** [npm/npm-audit-report#44]
Hi, as many other people I'm using npm 6. When I run `npm audit --parseable` I get a nice tabular output which has Y, N or nothing in the end of each line. Can someone explain to me what that means, because I couldn't figure that out from the source code.

Hare is an example of the output:
```
update  bl  high    npm update bl --depth 4 Remote Memory Exposure  https://npmjs.com/advisories/1555   exceljs>archiver>tar-stream>bl  N
review  cryptiles   high    >=4.1.2 Insufficient Entropy    https://npmjs.com/advisories/1464   uko-solr-client>request>hawk>cryptiles
install exceljs moderate    npm install exceljs@4.1.1   Cross-Site Scripting    https://npmjs.com/advisories/733    exceljs Y
review  hoek    moderate    > 4.2.0 < 5.0.0 || >= 5.0.3 Prototype Pollution https://npmjs.com/advisories/566    uko-solr-client>request>hawk>boom>hoek
```

**Comment by wraithgar** [comment]
It indicates that a breaking change is required to resolve the advisory

https://github.com/npm/npm-audit-report/blob/139002428f52ca5c08cbbe71e68fd31693672907/reporters/parseable.js#L27
