### ISSUE TITLE
Make a less verbose summary report

### ISSUE THREAD

**Issue by evilpacket** [npm/npm-audit-report#7]

**Comment by luislobo** [comment]
Does the `--parseable` option solves/closes this issue? https://github.com/npm/npm-audit-report/pull/21

**Comment by isaacs** [comment]
Closing out all issues and PRs from 2018 and 2019, since this module has been fundamentally refactored for version 2 (npm version 7).  Happy to reopen if this is still a thing worth exploring (and it'll probably be easier now if so).
